dockers:
  - image: g0194776/lightning-monkey-apiserver
    dockerfile: Dockerfile.apiserver
    # Path to the Dockerfile (from the project root).
    tag_templates:
    - "{{ .Tag }}"
    - latest
  - image: g0194776/lightning-monkey-agent
    dockerfile: Dockerfile.agent
    # Path to the Dockerfile (from the project root).
    tag_templates:
    - "{{ .Tag }}"
    - latest
