builds:
  - binary: lm-apiserver
    id: "apiserver"
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    main: ./cmd/apiserver
  - binary: lm-agent
    id: "agent"
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    main: ./cmd/agent

# Archive customization
archive:
  format: tar.gz


dockers:
#  - image: g0194776/lightning-monkey-apiserver
#    dockerfile: Dockerfile.apiserver
#    # Path to the Dockerfile (from the project root).
#    tag_templates:
#    - "{{ .Tag }}"
#    - latest
#    extra_files:
#    - dist/apiserver_linux_amd64/lm-apiserver
  - image: g0194776/lightning-monkey-agent
    dockerfile: Dockerfile.agent
    binary: lm-agent
    # Path to the Dockerfile (from the project root).
    tag_templates:
    - "{{ .Tag }}"
    - latest
    extra_files:
    - extras/kubernetes.repo
