FROM centos:7
COPY extras/kubernetes.repo /etc/yum.repos.d/kubernetes.repo
COPY lm-agent /opt

RUN yum install -y kubeadm-1.13.8-0 net-tools --disableexcludes=kubernetes
RUN chmod +x /opt/lm-agent && mkdir /tmp/cni && cp -r /opt/cni/bin/* /tmp/cni

#Update time zone to Asia-Shanghai
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
ENTRYPOINT /opt/lm-agent