FROM golang:1.10.2 as builder

COPY extras/kubernetes.repo ./kubernetes.repo
COPY lm-agent ./lm-agent
COPY prepare.sh ./prepare.sh
COPY init.sh ./init.sh
COPY download_kubeadm.sh ./download_kubeadm.sh
RUN  apt-get update -y && apt-get install jq -y && ./prepare.sh


FROM centos:7

ARG  K8S_VERSION_V1_12="1.12.10"
ARG  K8S_VERSION_V1_13="1.13.12"
ARG  K8S_VERSION_V1_14="1.14.10"
ARG  K8S_VERSION_V1_15="1.15.9"

RUN mkdir -p /usr/bin/k8s_${K8S_VERSION_V1_12} \
    && mkdir -p /usr/bin/k8s_${K8S_VERSION_V1_13} \
    && mkdir -p /usr/bin/k8s_${K8S_VERSION_V1_14} \
    && mkdir -p /usr/bin/k8s_${K8S_VERSION_V1_15}

COPY --from=builder /go/kubernetes.repo /etc/yum.repos.d/kubernetes.repo
COPY --from=builder /go/lm-agent /opt

COPY --from=builder /go/${K8S_VERSION_V1_12}/kubernetes/node/bin/kubeadm /usr/bin/k8s_${K8S_VERSION_V1_12}/kubeadm
COPY --from=builder /go/${K8S_VERSION_V1_13}/kubernetes/node/bin/kubeadm /usr/bin/k8s_${K8S_VERSION_V1_13}/kubeadm
COPY --from=builder /go/${K8S_VERSION_V1_14}/kubernetes/node/bin/kubeadm /usr/bin/k8s_${K8S_VERSION_V1_14}/kubeadm
COPY --from=builder /go/${K8S_VERSION_V1_15}/kubernetes/node/bin/kubeadm /usr/bin/k8s_${K8S_VERSION_V1_15}/kubeadm

RUN yum install -y net-tools
RUN chmod +x /opt/lm-agent && mkdir /tmp/cni && cp -r /opt/cni/bin/* /tmp/cni

#Update time zone to Asia-Shanghai
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
ENTRYPOINT /opt/lm-agent